"""
Legacy Vault PDF Generation Service
Generates professional 2-page Digital Will and Testament PDFs using ReportLab
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor, transparent
from reportlab.lib import colors
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from datetime import datetime
import io
from math import sin, cos, pi

# ═══════════════════════════════════════════════════════════
# COLOR SYSTEM
# ═══════════════════════════════════════════════════════════

COLORS = {
    'MAUVE': HexColor('#6b2d4e'),
    'MAUVE_MID': HexColor('#7a3458'),
    'MAUVE_LIGHT': HexColor('#c08fa8'),
    'BLUSH': HexColor('#f4c0d1'),
    'CREAM': HexColor('#fdf8f5'),
    'DARK': HexColor('#1a0810'),
    'TEXT_BODY': HexColor('#2c2c2a'),
    'TEXT_MID': HexColor('#4a4846'),
    'TEXT_LIGHT': HexColor('#999790'),
    'RULE': HexColor('#dedad4'),
    'RULE_DARK': HexColor('#c8c2bc'),
    'WHITE': HexColor('#ffffff'),
    'GREEN': HexColor('#2d6b3e'),
    'AMBER': HexColor('#8b4513'),
}

# ═══════════════════════════════════════════════════════════
# PAGE SETUP
# ═══════════════════════════════════════════════════════════

W, H = A4
ML = 20 * mm
MR = W - 20 * mm
CW = MR - ML

# ═══════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ═══════════════════════════════════════════════════════════

def draw_rounded_rect(c, x, y, width, height, radius, fill_color=None, stroke_color=None, stroke_width=1):
    """Draw a rounded rectangle"""
    if fill_color:
        c.setFillColor(fill_color)
    if stroke_color:
        c.setStrokeColor(stroke_color)
    if stroke_width:
        c.setLineWidth(stroke_width)
    
    c.roundRect(x, y, width, height, radius, fill=(fill_color is not None), stroke=(stroke_color is not None))

def draw_circle(c, cx, cy, radius, fill_color=None, stroke_color=None, stroke_width=0):
    """Draw a circle"""
    if fill_color:
        c.setFillColor(fill_color)
    if stroke_color:
        c.setStrokeColor(stroke_color)
    if stroke_width:
        c.setLineWidth(stroke_width)
    
    c.circle(cx, cy, radius, fill=(fill_color is not None), stroke=(stroke_color is not None))

def draw_line(c, x1, y1, x2, y2, color=None, width=0.5):
    """Draw a line"""
    if color:
        c.setStrokeColor(color)
    c.setLineWidth(width)
    c.line(x1, y1, x2, y2)

def roman_numeral(num):
    """Convert number to Roman numeral"""
    val = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1]
    syms = ['M', 'CM', 'D', 'CD', 'C', 'XC', 'L', 'XL', 'X', 'IX', 'V', 'IV', 'I']
    roman_num = ''
    i = 0
    while num > 0:
        for _ in range(num // val[i]):
            roman_num += syms[i]
            num -= val[i]
        i += 1
    return roman_num

def draw_page_background(c):
    """Draw page background and borders"""
    # Background
    c.setFillColor(COLORS['CREAM'])
    c.rect(0, 0, W, H, fill=True, stroke=False)
    
    # Left border
    c.setFillColor(COLORS['MAUVE'])
    c.rect(0, 0, 3.5*mm, H, fill=True, stroke=False)
    
    # Right border
    c.setFillColor(COLORS['MAUVE'])
    c.rect(W - 3.5*mm, 0, 3.5*mm, H, fill=True, stroke=False)

def draw_footer(c, page_num):
    """Draw footer on page"""
    footer_y = 11 * mm
    
    # Footer band
    c.setFillColor(COLORS['MAUVE'])
    c.rect(0, 0, W, footer_y, fill=True, stroke=False)
    
    # Accent line above footer
    draw_line(c, 0, footer_y + 0.6*mm, W, footer_y + 0.6*mm, COLORS['BLUSH'], 0.6)
    
    # Footer text
    c.setFont('Helvetica', 7)
    c.setFillColor(HexColor('#c4889e'))
    
    # Left text
    c.drawString(ML, footer_y + 4*mm, 'Generated by Legacy Vault  ·  legacyvault.com')
    
    # Center text
    center_text = 'LAST WILL AND TESTAMENT  —  MENVA SANESH'
    c.drawCentredString(W/2, footer_y + 4*mm, center_text)
    
    # Right text
    right_text = f'Instrument No. will_9_2026-05-09  ·  Page {page_num} of 2'
    c.drawRightString(MR, footer_y + 4*mm, right_text)

def draw_header_band_page1(c):
    """Draw header band for page 1"""
    header_height = 56 * mm
    
    # MAUVE background
    c.setFillColor(COLORS['MAUVE'])
    c.rect(0, H - header_height, W, header_height, fill=True, stroke=False)
    
    # Decorative circles top-right
    c.setFillColor(COLORS['MAUVE_MID'])
    c.circle(W, H, 46*mm, fill=True, stroke=False)
    c.setFillColor(COLORS['MAUVE'])
    c.circle(W, H, 26*mm, fill=True, stroke=False)
    
    # Accent line at bottom of header
    draw_line(c, 0, H - header_height, W, H - header_height, COLORS['BLUSH'], 0.7)
    
    # Wordmark
    c.setFont('Helvetica', 7)
    c.setFillColor(COLORS['BLUSH'])
    c.drawString(ML, H - 11*mm, 'L  E  G  A  C  Y     V  A  U  L  T')
    
    # Thin rule below wordmark
    draw_line(c, ML, H - 13.5*mm, ML + 62*mm, H - 13.5*mm, HexColor('#9e5070'), 0.4)
    
    # Main title
    c.setFont('Helvetica-Bold', 22)
    c.setFillColor(COLORS['WHITE'])
    c.drawString(ML, H - 28*mm, 'LAST WILL AND TESTAMENT')
    
    # Subtitle
    c.setFont('Helvetica-Bold', 11)
    c.setFillColor(COLORS['BLUSH'])
    c.drawString(ML, H - 36*mm, 'OF DIGITAL ASSETS AND ELECTRONIC PROPERTY')
    
    # Document meta right-aligned
    c.setFont('Helvetica', 7)
    c.setFillColor(HexColor('#c4889e'))
    c.drawRightString(MR, H - 44*mm, 'INSTRUMENT NO.  will_9_2026-05-09')
    c.drawRightString(MR, H - 49.5*mm, 'EXECUTED: 9th day of May, 2026  ·  CONFIDENTIAL')

def draw_preamble_box(c, y):
    """Draw preamble box and return new y position"""
    box_height = 32 * mm
    box_y = y - box_height
    
    # White rounded rectangle with border
    draw_rounded_rect(c, ML, box_y, CW, box_height, 2*mm, 
                     fill_color=COLORS['WHITE'], stroke_color=COLORS['RULE'], stroke_width=0.5)
    
    # Left strip (MAUVE)
    c.setFillColor(COLORS['MAUVE'])
    c.roundRect(ML, box_y, 5*mm, box_height, 2*mm, fill=True, stroke=False)
    c.rect(ML + 2*mm, box_y, 3*mm, box_height, fill=True, stroke=False)
    
    # Preamble text
    c.setFont('Helvetica', 8.5)
    c.setFillColor(COLORS['TEXT_MID'])
    
    preamble_text = (
        "KNOW ALL MEN BY THESE PRESENTS: I, MENVA SANESH, User Identification Number #9, "
        "domiciled and registered with Legacy Vault, being of sound and disposing mind and memory, "
        "and not acting under duress, menace, fraud, or undue influence of any person, do hereby "
        "make, publish, and declare this my Last Will and Testament of Digital Assets, hereby "
        "revoking all former digital wills, codicils, and testamentary dispositions of digital "
        "property heretofore made by me."
    )
    
    text_x = ML + 8*mm
    text_width = CW - 8*mm - 2*mm
    lines = wrap_text(preamble_text, c, text_width, 8.5)
    
    line_y = box_y + box_height - 4*mm
    for line in lines:
        c.drawString(text_x, line_y, line)
        line_y -= 14
    
    return box_y - 37*mm

def draw_article_heading(c, label, title, y):
    """Draw article heading and return new y position"""
    # Article label
    c.setFont('Helvetica-Bold', 7)
    c.setFillColor(COLORS['MAUVE'])
    c.drawString(ML, y, label)
    
    # BLUSH dot
    c.setFillColor(COLORS['BLUSH'])
    c.circle(ML + 25*mm, y + 0.8*mm, 1.1*mm, fill=True, stroke=False)
    
    # Title
    c.setFont('Helvetica-Bold', 10.5)
    c.setFillColor(COLORS['MAUVE'])
    c.drawString(ML + 29*mm, y, title)
    
    # Rule line
    draw_line(c, ML, y - 2.5*mm, MR, y - 2.5*mm, COLORS['RULE'], 0.5)
    
    return y - 2.5*mm

def wrap_text(text, c, width, font_size):
    """Simple text wrapping"""
    c.setFont('Helvetica', font_size)
    words = text.split()
    lines = []
    current_line = []
    
    for word in words:
        test_line = ' '.join(current_line + [word])
        if c.stringWidth(test_line, 'Helvetica', font_size) <= width:
            current_line.append(word)
        else:
            if current_line:
                lines.append(' '.join(current_line))
            current_line = [word]
    
    if current_line:
        lines.append(' '.join(current_line))
    
    return lines

def draw_field_grid(c, y, fields):
    """Draw 2-column field grid"""
    col_width = CW / 2
    row_height = 13 * mm
    
    for row, (field1, value1, field2, value2) in enumerate(fields):
        row_y = y - (row * row_height)
        
        # Column 1
        c.setFont('Helvetica', 6.5)
        c.setFillColor(COLORS['TEXT_LIGHT'])
        c.drawString(ML, row_y - 3*mm, field1)
        
        c.setFont('Helvetica-Bold', 10)
        c.setFillColor(COLORS['DARK'])
        c.drawString(ML, row_y - 8.5*mm, value1)
        
        draw_line(c, ML, row_y - 10.5*mm, ML + col_width - 5*mm, row_y - 10.5*mm, COLORS['RULE'], 0.5)
        
        # Column 2
        c.setFont('Helvetica', 6.5)
        c.setFillColor(COLORS['TEXT_LIGHT'])
        c.drawString(ML + col_width, row_y - 3*mm, field2)
        
        c.setFont('Helvetica-Bold', 10)
        c.setFillColor(COLORS['DARK'])
        c.drawString(ML + col_width, row_y - 8.5*mm, value2)
        
        draw_line(c, ML + col_width, row_y - 10.5*mm, MR, row_y - 10.5*mm, COLORS['RULE'], 0.5)
    
    return y - (len(fields) * row_height)

def draw_asset_card(c, y, roman_num, asset_name, asset_type, description, location, date):
    """Draw asset card and return new y position"""
    card_height = 16 * mm
    card_y = y - card_height
    
    # Drop shadow
    c.setFillColor(HexColor('#e8e0da'))
    c.roundRect(ML + 0.6*mm, card_y - 0.6*mm, CW, card_height, 2*mm, fill=True, stroke=False)
    
    # White card
    draw_rounded_rect(c, ML, card_y, CW, card_height, 2*mm,
                     fill_color=COLORS['WHITE'], stroke_color=COLORS['RULE'], stroke_width=0.4)
    
    # Left strip
    c.setFillColor(COLORS['MAUVE'])
    c.roundRect(ML, card_y, 6*mm, card_height, 2*mm, fill=True, stroke=False)
    c.rect(ML + 2*mm, card_y, 4*mm, card_height, fill=True, stroke=False)
    
    # Roman numeral in strip
    c.setFont('Helvetica-Bold', 7)
    c.setFillColor(COLORS['WHITE'])
    c.drawCentredString(ML + 3*mm, card_y + card_height/2 - 1.5*mm, roman_num)
    
    # Asset name
    c.setFont('Helvetica-Bold', 10)
    c.setFillColor(COLORS['DARK'])
    c.drawString(ML + 9*mm, card_y + card_height - 5.5*mm, asset_name)
    
    # Type badge
    c.setFillColor(COLORS['BLUSH'])
    c.roundRect(ML + 9*mm + c.stringWidth(asset_name, 'Helvetica-Bold', 10) + 2*mm,
               card_y + card_height - 7*mm, 30*mm, 4.2*mm, 1.2*mm, fill=True, stroke=False)
    
    c.setFont('Helvetica', 6.5)
    c.setFillColor(COLORS['MAUVE'])
    c.drawString(ML + 9*mm + c.stringWidth(asset_name, 'Helvetica-Bold', 10) + 4.5*mm,
                card_y + card_height - 6.5*mm, asset_type)
    
    # Description
    c.setFont('Helvetica', 8)
    c.setFillColor(COLORS['TEXT_MID'])
    c.drawString(ML + 9*mm, card_y + card_height - 11*mm, description)
    
    # Right meta
    c.setFont('Helvetica', 7)
    c.setFillColor(COLORS['TEXT_LIGHT'])
    c.drawRightString(MR - 2*mm, card_y + card_height - 5.5*mm, f'Location: {location}')
    c.drawRightString(MR - 2*mm, card_y + card_height - 11*mm, f'Recorded: {date}')
    
    return card_y - 2*mm

def draw_executor_card(c, y, roman_num, name, email, permission, status, access_granted, date):
    """Draw executor card and return new y position"""
    card_height = 17 * mm
    card_y = y - card_height
    
    # Drop shadow
    c.setFillColor(HexColor('#e8e0da'))
    c.roundRect(ML + 0.6*mm, card_y - 0.6*mm, CW, card_height, 2*mm, fill=True, stroke=False)
    
    # White card
    draw_rounded_rect(c, ML, card_y, CW, card_height, 2*mm,
                     fill_color=COLORS['WHITE'], stroke_color=COLORS['RULE'], stroke_width=0.4)
    
    # Left strip (MAUVE_LIGHT)
    c.setFillColor(COLORS['MAUVE_LIGHT'])
    c.roundRect(ML, card_y, 6*mm, card_height, 2*mm, fill=True, stroke=False)
    c.rect(ML + 2*mm, card_y, 4*mm, card_height, fill=True, stroke=False)
    
    # Roman numeral
    c.setFont('Helvetica-Bold', 7)
    c.setFillColor(COLORS['WHITE'])
    c.drawCentredString(ML + 3*mm, card_y + card_height/2 - 1.5*mm, roman_num)
    
    # Name
    c.setFont('Helvetica-Bold', 10)
    c.setFillColor(COLORS['DARK'])
    c.drawString(ML + 9*mm, card_y + card_height - 5.5*mm, name)
    
    # Email
    c.setFont('Helvetica', 8)
    c.setFillColor(COLORS['TEXT_MID'])
    c.drawString(ML + 9*mm, card_y + card_height - 10.5*mm, email)
    
    # Appointed date
    c.setFont('Helvetica', 7)
    c.setFillColor(COLORS['TEXT_LIGHT'])
    c.drawString(ML + 9*mm, card_y + card_height - 14.5*mm, f'Appointed: {date}')
    
    # Right side columns
    col_positions = [MR - 68*mm, MR - 44*mm, MR - 22*mm]
    labels = ['PERMISSION', 'STATUS', 'ACCESS']
    values = [permission, status, 'Granted' if access_granted else 'Pending']
    
    for i, (col_x, label, value) in enumerate(zip(col_positions, labels, values)):
        c.setFont('Helvetica', 6.5)
        c.setFillColor(COLORS['TEXT_LIGHT'])
        c.drawString(col_x, card_y + card_height - 4.5*mm, label)
        
        c.setFont('Helvetica-Bold', 8.5)
        if label == 'STATUS':
            color = COLORS['GREEN'] if value == 'Approved' else COLORS['MAUVE']
        elif label == 'ACCESS':
            color = COLORS['GREEN'] if access_granted else COLORS['AMBER']
        else:
            color = COLORS['TEXT_BODY']
        
        c.setFillColor(color)
        c.drawString(col_x, card_y + card_height - 9.5*mm, value)
    
    return card_y - 2*mm

def draw_disclaimer_card(c, y):
    """Draw Article IV disclaimer card and return new y position"""
    card_height = 28 * mm
    card_y = y - card_height
    
    # White rounded card
    draw_rounded_rect(c, ML, card_y, CW, card_height, 2*mm,
                     fill_color=COLORS['WHITE'], stroke_color=COLORS['RULE'], stroke_width=0.4)
    
    # Left strip (BLUSH)
    c.setFillColor(COLORS['BLUSH'])
    c.roundRect(ML, card_y, 5*mm, card_height, 2*mm, fill=True, stroke=False)
    c.rect(ML + 2*mm, card_y, 3*mm, card_height, fill=True, stroke=False)
    
    # Disclaimer text
    c.setFont('Helvetica', 7.8)
    c.setFillColor(COLORS['TEXT_MID'])
    
    disclaimer = (
        "This instrument has been generated by LEGACY VAULT and constitutes a formal record of "
        "the Testator's digital estate. This document is intended to supplement — and not replace — a "
        "legally executed will under the laws of the applicable jurisdiction. The Testator is strongly "
        "advised to seek independent legal counsel to give this instrument full binding legal effect. "
        "This record shall be reviewed and updated periodically to reflect any change in the Testator's "
        "digital estate or personal circumstances. Legacy Vault accepts no liability for the legal "
        "validity of this instrument in any jurisdiction."
    )
    
    text_x = ML + 8*mm
    text_width = CW - 8*mm - 2*mm
    lines = wrap_text(disclaimer, c, text_width, 7.8)
    
    line_y = card_y + card_height - 4*mm
    for line in lines:
        c.drawString(text_x, line_y, line)
        line_y -= 12
    
    return card_y - 5*mm

def draw_signature_box(c, x, y, width, label, prefill=''):
    """Draw signature box"""
    box_height = 22 * mm
    
    # White rounded card
    draw_rounded_rect(c, x, y - box_height, width, box_height, 1.5*mm,
                     fill_color=COLORS['WHITE'], stroke_color=COLORS['RULE'], stroke_width=0.4)
    
    # Top band
    c.setFillColor(HexColor('#f5ede9'))
    c.roundRect(x, y - 7*mm, width, 7*mm, 1.5*mm, fill=True, stroke=False)
    
    # Label
    c.setFont('Helvetica', 6.5)
    c.setFillColor(COLORS['MAUVE'])
    c.drawString(x + 3*mm, y - 4.5*mm, label.upper())
    
    # Signature line
    draw_line(c, x + 4*mm, y - 16*mm, x + width - 4*mm, y - 16*mm, COLORS['MAUVE_LIGHT'], 0.6)
    
    # Prefill or placeholder
    if prefill:
        c.setFont('Helvetica', 8.5)
        c.setFillColor(COLORS['TEXT_MID'])
        c.drawString(x + 4*mm, y - 14*mm, prefill)
    else:
        c.setFont('Helvetica', 12)
        c.setFillColor(COLORS['TEXT_LIGHT'])
        c.drawString(x + 4*mm, y - 15.5*mm, '✕')

def draw_notary_seal(c, cx, cy):
    """Draw notary seal circle"""
    # Outer circle
    c.setFillColor(COLORS['CREAM'])
    c.setStrokeColor(COLORS['MAUVE_LIGHT'])
    c.setLineWidth(0.8)
    c.circle(cx, cy, 18*mm, fill=True, stroke=True)
    
    # Inner circle
    c.setFillColor(transparent)
    c.setStrokeColor(HexColor('#d4b0c0'))
    c.setLineWidth(0.4)
    c.circle(cx, cy, 15*mm, fill=False, stroke=True)
    
    # Text
    c.setFont('Helvetica-Bold', 6.5)
    c.setFillColor(COLORS['MAUVE_LIGHT'])
    c.drawCentredString(cx, cy + 3*mm, 'OFFICIAL')
    c.drawCentredString(cx, cy + 0*mm, 'NOTARY')
    c.drawCentredString(cx, cy - 3*mm, 'SEAL')

# ═══════════════════════════════════════════════════════════
# MAIN PDF GENERATION FUNCTION
# ═══════════════════════════════════════════════════════════

def generate_will_pdf(user_data=None):
    """
    Generate a Digital Will and Testament PDF
    
    user_data dict should contain:
    {
        'id': int,
        'full_name': str,
        'email': str,
        'date_of_birth': str (YYYY-MM-DD),
        'assets': [
            {'name': str, 'type': str, 'description': str, 'location': str, 'created_at': str},
            ...
        ],
        'executors': [
            {'name': str, 'email': str, 'permission': str, 'status': str, 'access_granted': bool, 'created_at': str},
            ...
        ]
    }
    
    Returns: bytes (PDF content)
    """
    
    # Default data if none provided
    if not user_data:
        user_data = {
            'id': 9,
            'full_name': 'MENVA SANESH',
            'email': 'menva@gmail.com',
            'date_of_birth': '1991-04-27',
            'assets': [
                {'name': 'INSTAGRAM', 'type': 'Social Media', 'description': 'My private Instagram account', 'location': '—', 'created_at': '2026-05-09'},
                {'name': 'BANKING APP', 'type': 'Bank Account', 'description': 'SBI banking application', 'location': 'SBI Branch', 'created_at': '2026-04-27'},
                {'name': 'MY PHOTOS', 'type': 'Digital Photography', 'description': 'Personal photograph collection', 'location': 'gallery/photos', 'created_at': '2026-04-27'},
            ],
            'executors': [
                {'name': 'MENU', 'email': 'menvasanesh27@gmail.com', 'permission': 'View Only', 'status': 'Approved', 'access_granted': True, 'created_at': '2026-05-09'},
                {'name': 'ABHINAV', 'email': 'abhinavbijusn@gmail.com', 'permission': 'View Only', 'status': 'Approved', 'access_granted': False, 'created_at': '2026-05-09'},
            ]
        }
    
    # Create PDF in memory
    pdf_buffer = io.BytesIO()
    c = canvas.Canvas(pdf_buffer, pagesize=A4)
    
    # Set metadata
    c.setTitle(f"Last Will and Testament of Digital Assets — {user_data['full_name']}")
    c.setAuthor('Legacy Vault')
    c.setSubject('Last Will and Testament of Digital Assets')
    c.setKeywords('digital will, legacy vault, digital inheritance, testament')
    
    # ═══════════════════════════════════════════════════════════
    # PAGE 1 — MAIN DOCUMENT
    # ═══════════════════════════════════════════════════════════
    
    draw_page_background(c)
    draw_header_band_page1(c)
    
    y = H - 56*mm - 8*mm  # Below header
    
    # Preamble box
    y = draw_preamble_box(c, y)
    y -= 6*mm
    draw_line(c, ML, y, MR, y, COLORS['MAUVE_LIGHT'], 0.5)
    y -= 6*mm
    
    # ARTICLE I — GRANTOR IDENTIFICATION
    y = draw_article_heading(c, 'ARTICLE  I', 'GRANTOR IDENTIFICATION', y)
    y -= 5*mm
    
    fields = [
        ('FULL LEGAL NAME', 'MENVA SANESH', 'DATE OF BIRTH / REG.', 'April 27, 2026'),
        ('EMAIL ADDRESS', user_data['email'], 'USER IDENTIFICATION', f"Legacy Vault ID #{user_data['id']}"),
    ]
    
    y = draw_field_grid(c, y, fields)
    y -= 6*mm
    draw_line(c, ML, y, MR, y, COLORS['MAUVE_LIGHT'], 0.5)
    y -= 6*mm
    
    # ARTICLE II — SCHEDULE OF DIGITAL ASSETS
    y = draw_article_heading(c, 'ARTICLE  II', 'SCHEDULE OF DIGITAL ASSETS', y)
    y -= 5*mm
    
    # Intro text
    c.setFont('Helvetica-Oblique', 8)
    c.setFillColor(COLORS['TEXT_MID'])
    intro_text = (
        "I give, bequeath, and devise the following digital assets, being the whole of my electronic "
        "estate, as specifically enumerated herein. Each asset shall pass to the designated Executor(s) "
        "in accordance with the permissions granted under Article III:"
    )
    lines = wrap_text(intro_text, c, CW, 8)
    for line in lines:
        c.drawString(ML, y, line)
        y -= 12.5
    
    y -= 2*mm
    
    # Asset cards
    for i, asset in enumerate(user_data['assets'][:3]):  # Limit to 3 assets
        roman = roman_numeral(i + 1)
        y = draw_asset_card(c, y, roman, asset['name'], asset['type'], 
                           asset['description'], asset['location'], asset['created_at'][-10:])
    
    y -= 5*mm
    draw_line(c, ML, y, MR, y, COLORS['MAUVE_LIGHT'], 0.5)
    y -= 6*mm
    
    # ARTICLE III — APPOINTMENT OF EXECUTORS
    y = draw_article_heading(c, 'ARTICLE  III', 'APPOINTMENT OF PERSONAL EXECUTORS', y)
    y -= 5*mm
    
    # Intro text
    c.setFont('Helvetica-Oblique', 8)
    c.setFillColor(COLORS['TEXT_MID'])
    intro_text = (
        "I hereby nominate, constitute, and appoint the following named individuals as Personal Executors "
        "of my digital estate. Each Executor shall serve in a fiduciary capacity and shall have only such "
        "authority as is expressly granted herein:"
    )
    lines = wrap_text(intro_text, c, CW, 8)
    for line in lines:
        c.drawString(ML, y, line)
        y -= 12.5
    
    y -= 2*mm
    
    # Executor cards
    for i, executor in enumerate(user_data['executors'][:2]):  # Limit to 2 executors
        roman = roman_numeral(i + 1)
        y = draw_executor_card(c, y, roman, executor['name'], executor['email'],
                              executor['permission'], executor['status'],
                              executor['access_granted'], executor['created_at'][-10:])
    
    y -= 5*mm
    draw_line(c, ML, y, MR, y, COLORS['MAUVE_LIGHT'], 0.5)
    y -= 6*mm
    
    # Check if we need to continue on next page
    if y < 100*mm:
        c.showPage()
        draw_page_background(c)
        y = H - 20*mm
    else:
        # ARTICLE IV on page 1
        y = draw_article_heading(c, 'ARTICLE  IV', 'GOVERNING TERMS AND LEGAL DISCLAIMER', y)
        y -= 5*mm
        y = draw_disclaimer_card(c, y)
        y -= 8*mm
    
    draw_footer(c, 1)
    
    # ═══════════════════════════════════════════════════════════
    # PAGE 2 — SIGNATURE PAGE
    # ═══════════════════════════════════════════════════════════
    
    c.showPage()
    draw_page_background(c)
    
    # Header for page 2
    header_height = 38 * mm
    c.setFillColor(COLORS['MAUVE'])
    c.rect(0, H - header_height, W, header_height, fill=True, stroke=False)
    
    draw_line(c, 0, H - header_height, W, H - header_height, COLORS['BLUSH'], 0.7)
    
    # Wordmark
    c.setFont('Helvetica', 7)
    c.setFillColor(COLORS['BLUSH'])
    c.drawString(ML, H - 11*mm, 'L  E  G  A  C  Y     V  A  U  L  T')
    
    # Title
    c.setFont('Helvetica-Bold', 18)
    c.setFillColor(COLORS['WHITE'])
    c.drawString(ML, H - 26*mm, 'SIGNATURE AND EXECUTION PAGE')
    
    # Right meta
    c.setFont('Helvetica', 7)
    c.setFillColor(HexColor('#c4889e'))
    c.drawRightString(MR, H - 26*mm, 'Instrument No. will_9_2026-05-09')
    c.drawRightString(MR, H - 31*mm, f'Last Will and Testament of {user_data["full_name"]}')
    
    y = H - 46*mm
    
    # EXECUTION STATEMENT
    c.setFont('Helvetica', 9)
    c.setFillColor(COLORS['TEXT_BODY'])
    
    exec_text = (
        "IN WITNESS WHEREOF, I, MENVA SANESH, the Testator named in this Last Will and "
        "Testament of Digital Assets, have hereunto set my hand and seal to this, my Last Will and "
        "Testament, on this 9th day of May, in the year Two Thousand and Twenty-Six, declaring "
        "and publishing this as my Last Will and Testament of Digital Assets, in the presence of the "
        "witnesses whose signatures appear below, each of whom signed in my presence and in the "
        "presence of each other."
    )
    
    lines = wrap_text(exec_text, c, CW, 9)
    for line in lines:
        c.drawString(ML, y, line)
        y -= 15
    
    y -= 13*mm
    draw_line(c, ML, y, MR, y, COLORS['RULE_DARK'], 0.5)
    y -= 8*mm
    
    # TESTATOR SIGNATURE SECTION
    c.setFont('Helvetica-Bold', 9)
    c.setFillColor(COLORS['MAUVE'])
    c.drawString(ML, y, 'TESTATOR')
    
    y -= 6*mm
    c.setFont('Helvetica', 8.5)
    c.setFillColor(COLORS['TEXT_MID'])
    c.drawString(ML, y, 'I, MENVA SANESH, sign my name to this instrument this 9th day of May, 2026,')
    y -= 5*mm
    c.drawString(ML, y, 'and being first duly sworn, declare to the undersigned authority that I sign')
    y -= 5*mm
    c.drawString(ML, y, 'and execute this instrument as my Last Will and that I sign it willingly.')
    
    y -= 12*mm
    draw_signature_box(c, ML, y, 80*mm, 'Signature of Testator', 'MENVA SANESH')
    draw_signature_box(c, ML + 90*mm, y, 80*mm, 'Date', '9th May, 2026')
    
    y -= 28*mm
    draw_line(c, ML, y, MR, y, COLORS['RULE_DARK'], 0.5)
    y -= 8*mm
    
    # ATTESTATION OF WITNESSES
    c.setFont('Helvetica-Bold', 9)
    c.setFillColor(COLORS['MAUVE'])
    c.drawString(ML, y, 'ATTESTATION OF WITNESSES')
    
    y -= 6*mm
    c.setFont('Helvetica', 8.5)
    c.setFillColor(COLORS['TEXT_MID'])
    
    witness_text = (
        "We, the undersigned witnesses, each do hereby declare that the Testator signed and executed "
        "this instrument as their Last Will and Testament of Digital Assets in the presence of us, both "
        "present at the same time; and that we, in the Testator's presence, at their request, and in the "
        "presence of each other, have subscribed our names hereto as witnesses thereof, and that to the "
        "best of our knowledge the Testator was at the time of signing of sound and disposing mind and memory."
    )
    
    lines = wrap_text(witness_text, c, CW, 8.5)
    for line in lines:
        c.drawString(ML, y, line)
        y -= 13.5
    
    y -= 13*mm
    
    # Witness signature boxes
    draw_signature_box(c, ML, y, 80*mm, 'Witness No. 1 — Signature', '')
    draw_signature_box(c, ML + 90*mm, y, 80*mm, 'Witness No. 1 — Full Name (Print)', '')
    
    y -= 28*mm
    draw_signature_box(c, ML, y, 80*mm, 'Witness No. 2 — Signature', '')
    draw_signature_box(c, ML + 90*mm, y, 80*mm, 'Witness No. 2 — Full Name (Print)', '')
    
    y -= 28*mm
    draw_line(c, ML, y, MR, y, COLORS['RULE_DARK'], 0.5)
    y -= 8*mm
    
    # NOTARIAL ACKNOWLEDGEMENT
    c.setFont('Helvetica-Bold', 9)
    c.setFillColor(COLORS['MAUVE'])
    c.drawString(ML, y, 'NOTARIAL ACKNOWLEDGEMENT  /  OFFICIAL SEAL')
    
    y -= 6*mm
    c.setFont('Helvetica', 8.5)
    c.setFillColor(COLORS['TEXT_MID'])
    
    notary_text = (
        "State / Jurisdiction of ________________    County / District of ________________\n\n"
        "Subscribed, sworn to and acknowledged before me by MENVA SANESH, the Testator,\n"
        "and subscribed and sworn to before me by ________________ and ________________,\n"
        "witnesses, this ______ day of ______________, 20___."
    )
    
    for line in notary_text.split('\n'):
        c.drawString(ML, y, line)
        y -= 14
    
    # Notary seal
    draw_notary_seal(c, MR - 20*mm, y + 20*mm)
    
    y -= 12*mm
    draw_signature_box(c, ML, y, 100*mm, 'Notary Public — Signature & Commission No.', '')
    
    y -= 28*mm
    draw_line(c, ML, y, MR, y, COLORS['RULE_DARK'], 0.5)
    y -= 6*mm
    
    # Final certification line
    c.setFont('Helvetica', 7.5)
    c.setFillColor(COLORS['TEXT_LIGHT'])
    cert_text = 'This document was digitally generated by Legacy Vault · Instrument No. will_9_2026-05-09 · May 9, 2026'
    c.drawCentredString(W/2, y, cert_text)
    
    draw_footer(c, 2)
    
    # ═══════════════════════════════════════════════════════════
    # SAVE AND RETURN
    # ═══════════════════════════════════════════════════════════
    
    c.save()
    pdf_bytes = pdf_buffer.getvalue()
    pdf_buffer.close()
    
    return pdf_bytes

# For testing and stdin/stdout handling
if __name__ == '__main__':
    import json
    import sys
    
    # Read user data from stdin
    user_data = None
    try:
        input_data = sys.stdin.read()
        if input_data:
            user_data = json.loads(input_data)
    except json.JSONDecodeError:
        pass
    
    # Generate PDF
    pdf = generate_will_pdf(user_data)
    
    # Write binary PDF to stdout
    sys.stdout.buffer.write(pdf)
    sys.stdout.buffer.flush()
