const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { getUserById } = require('../models/userModel');
const { getAssetsByUserId } = require('../models/assetModel');
const { getExecutorsByUserId } = require('../models/executorModel');
const { saveGeneratedWill } = require('../models/willModel');

// Generate Digital Will PDF
const generateDigitalWill = async (req, res) => {
  try {
    const userId = req.user.id;

    // Fetch user details
    const user = await getUserById(userId);
    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }

    // Fetch user assets
    const assets = await getAssetsByUserId(userId);

    // Fetch user executors
    const executors = await getExecutorsByUserId(userId);

    // Get primary executor (first one, or approved one)
    const primaryExecutor = executors.length > 0 ? executors[0] : null;

    // Create PDF document
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50,
      bufferPages: true
    });

    // Generate filename
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `will_${userId}_${timestamp}.pdf`;
    const filepath = path.join(__dirname, '../generated_wills', filename);

    // Create write stream
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    // ===== Header =====
    doc.fontSize(24).font('Helvetica-Bold').text('DIGITAL WILL', { align: 'center' });
    doc.moveDown(0.2);
    doc.fontSize(10).font('Helvetica').text('Generated by LEGACY VAULT', { align: 'center' });
    doc.moveDown(0.5);

    // ===== User Information Section =====
    doc.fontSize(14).font('Helvetica-Bold').text('1. GRANTOR INFORMATION');
    doc.moveDown(0.3);
    doc.fontSize(11).font('Helvetica').text(`Name: ${user.first_name || 'Not provided'} ${user.last_name || ''}`.trim());
    doc.text(`Email: ${user.email}`);
    doc.text(`User ID: ${user.id}`);
    doc.text(`Document Created: ${new Date().toLocaleString()}`);
    doc.moveDown(0.5);

    // ===== Digital Assets Section =====
    doc.fontSize(14).font('Helvetica-Bold').text('2. DIGITAL ASSETS');
    if (assets && assets.length > 0) {
      doc.moveDown(0.3);
      const actionLabels = { pass: 'Pass credentials to Executor', delete: 'Delete Account', last_message: 'Send Final Message' };
      assets.forEach((asset, index) => {
        doc.fontSize(11).font('Helvetica-Bold').text(`Asset ${index + 1}: ${asset.asset_name}`);
        doc.fontSize(10).font('Helvetica')
          .text(`Type: ${asset.asset_type}`)
          .text(`Account/Email: ${asset.email || 'N/A'}`)
          .text(`Description: ${asset.description || 'N/A'}`)
          .text(`Inheritance Action: ${actionLabels[asset.action_type] || 'Pass credentials to Executor'}`);
        if (asset.action_type === 'last_message' && asset.last_message) {
          doc.text(`Farewell Message: "${asset.last_message}"`);
        }
        doc.text(`Registered: ${new Date(asset.created_at).toLocaleDateString()}`);
        doc.moveDown(0.3);
      });
    } else {
      doc.fontSize(11).font('Helvetica').text('No digital assets registered.');
      doc.moveDown(0.3);
    }
    doc.moveDown(0.5);

    // ===== Executors Section =====
    doc.fontSize(14).font('Helvetica-Bold').text('3. DESIGNATED EXECUTORS');
    if (executors && executors.length > 0) {
      doc.moveDown(0.3);
      executors.forEach((executor, index) => {
        doc.fontSize(11).font('Helvetica-Bold').text(`Executor ${index + 1}: ${executor.executor_name}`);
        doc.fontSize(10).font('Helvetica')
          .text(`Email: ${executor.executor_email}`)
          .text(`Permissions: ${executor.permissions || 'view'}`)
          .text(`Status: ${executor.status}`)
          .text(`Access Granted: ${executor.is_active ? 'Yes' : 'No'}`)
          .text(`Assigned: ${new Date(executor.created_at).toLocaleDateString()}`);
        doc.moveDown(0.3);
      });
    } else {
      doc.fontSize(11).font('Helvetica').text('No executors designated. Please add executors before publishing.');
      doc.moveDown(0.3);
    }
    doc.moveDown(0.5);

    // ===== Legal Disclaimer Section =====
    doc.fontSize(14).font('Helvetica-Bold').text('4. LEGAL DISCLAIMER');
    doc.moveDown(0.3);
    const disclaimer = `This Digital Will is generated by LEGACY VAULT and serves as a record of your digital assets and executor designations. This document is intended to supplement, not replace, legal advice. For a binding will with legal effect, please consult with an attorney licensed in your jurisdiction. This digital record should be reviewed regularly and updated as your circumstances change.`;
    doc.fontSize(10).font('Helvetica').text(disclaimer, { align: 'left', width: 500 });
    doc.moveDown(0.5);

    // ===== Footer =====
    doc.fontSize(9).font('Helvetica').text(`Generated on ${new Date().toLocaleString()}`, { align: 'center' });
    doc.text(`Document ID: ${filename}`, { align: 'center' });

    // Finalize PDF
    doc.end();

    // Handle stream completion
    stream.on('finish', async () => {
      try {
        // Store in database with real data
        const willTitle = `Digital Will - ${user.first_name || 'User'} ${user.last_name || ''}`.trim();
        
        // Build detailed description with actual asset names
        const assetList = assets.length > 0 
          ? assets.map(a => `${a.asset_name} (${a.asset_type})`).join(', ')
          : 'None';
        const willDescription = `Auto-generated digital will containing ${assets.length} asset(s) and ${executors.length} executor(s)\n\nAssets: ${assetList}`;
        
        // Build detailed content with executor details
        let willContent = `Digital Will for ${user.first_name || 'User'} ${user.last_name || ''}\n\n`;
        willContent += `ASSETS (${assets.length}):\n`;
        const actionLabels = { pass: 'Pass to Executor', delete: 'Delete Account', last_message: 'Final Message' };
        if (assets.length > 0) {
          assets.forEach((asset, i) => {
            willContent += `${i+1}. ${asset.asset_name} (${asset.asset_type})\n`;
            willContent += `   Account: ${asset.email || 'N/A'}\n`;
            willContent += `   Action: ${actionLabels[asset.action_type] || 'Pass to Executor'}\n`;
            if (asset.action_type === 'last_message' && asset.last_message) {
              willContent += `   Farewell Message: "${asset.last_message}"\n`;
            }
            willContent += `   Description: ${asset.description || 'N/A'}\n`;
          });
        } else {
          willContent += 'None registered\n';
        }
        willContent += `\nEXECUTORS (${executors.length}):\n`;
        if (executors.length > 0) {
          executors.forEach((executor, i) => {
            willContent += `${i+1}. ${executor.executor_name}\n   Email: ${executor.executor_email}\n   Permissions: ${executor.permissions || 'view'}\n`;
          });
        } else {
          willContent += 'None designated\n';
        }

        // Store file path relative to backend directory
        const relativeFilePath = `generated_wills/${filename}`;

        const will = await saveGeneratedWill(
          userId,
          willTitle,
          willDescription,
          willContent,
          relativeFilePath,
          primaryExecutor ? primaryExecutor.id : null
        );

        res.status(201).json({
          message: 'Digital will generated successfully',
          will: {
            id: will.id,
            title: will.title,
            description: will.description,
            file_path: will.file_path,
            status: will.status,
            created_at: will.created_at,
            assets: {
              count: assets.length,
              items: assets.map(a => ({ id: a.id, name: a.asset_name, type: a.asset_type }))
            },
            executors: {
              count: executors.length,
              items: executors.map(e => ({ id: e.id, name: e.executor_name, email: e.executor_email }))
            }
          },
          download_url: `/generated_wills/${filename}`
        });
      } catch (err) {
        console.error('Error saving will to database:', err);
        res.status(500).json({ error: 'Failed to save will to database' });
      }
    });

    stream.on('error', (err) => {
      console.error('Stream error:', err);
      res.status(500).json({ error: 'Failed to generate PDF' });
    });
  } catch (err) {
    console.error('Generate will error:', err);
    res.status(500).json({ error: 'Failed to generate digital will' });
  }
};

module.exports = {
  generateDigitalWill
};
